#UMB SAN JOSE DEL RINCON
#INGENIERIA EN SISTEMAS COMPUTACIONALES
#PROGRAMACION OTIENTADA A OBJETOS
#CARLOS ENRIQUE CORONA NUÑEZ

print("Programa 1: FUNCION SALUDAR")

nombre=input("¿Cual es tu nombre?:")
saludar=input("Hola"+nombre)